/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // // By default, Docusaurus generates a sidebar from the docs folder structure
  integrationsSidebar: [
    { type: "doc", id: "integrations/index" },
    {
      type: "category",
      label: "Coding Agents & AI Tools",
      link: {
        type: "generated-index",
        title: "AI Tools",
        description: "Integrate LiteLLM with AI tools like OpenWebUI, Claude Code, and more",
        slug: "/ai_tools"
      },
      items: [
        {
          type: "doc",
          id: "tutorials/openweb_ui",
          customProps: { icon: "/img/integrations/openwebui.png" },
        },
        {
          type: "category",
          label: "Claude Code",
          customProps: { icon: "/img/integrations/anthropic.png" },
          items: [
            "claude_code_compatibility",
            "tutorials/claude_code_cut_costs",
            "tutorials/claude_code_autorouter",
            "tutorials/claude_responses_api",
            "tutorials/claude_code_okta_sso",
            "tutorials/claude_code_gateway",
            "tutorials/claude_code_max_subscription",
            "tutorials/claude_code_byok",
            "tutorials/claude_code_customer_tracking",
            "tutorials/claude_code_budget_statusline",
            "tutorials/claude_code_prompt_cache_routing",
            "tutorials/claude_code_websearch",
            "tutorials/claude_mcp",
            "tutorials/claude_non_anthropic_models",
            "tutorials/claude_code_plugin_marketplace",
            "tutorials/claude_code_beta_headers",
            "claude_code_context_management",
          ]
        },
        {
          type: "doc",
          id: "tutorials/claude_desktop_cowork",
          customProps: { icon: "/img/integrations/anthropic.png" },
        },
        {
          type: "doc",
          id: "tutorials/opencode_integration",
          customProps: { icon: "/img/integrations/opencode.png" },
        },
        {
          type: "doc",
          id: "tutorials/openclaw_integration",
          customProps: { icon: "/img/integrations/openclaw.png" },
        },
        {
          type: "doc",
          id: "tutorials/cursor_integration",
          customProps: { icon: "/img/integrations/cursor.png" },
        },
        {
          type: "doc",
          id: "tutorials/github_copilot_integration",
          customProps: { icon: "/img/integrations/github-copilot.png" },
        },
        {
          type: "doc",
          id: "tutorials/litellm_gemini_cli",
          customProps: { icon: "/img/integrations/google.png" },
        },
        {
          type: "doc",
          id: "tutorials/litellm_qwen_code_cli",
          customProps: { icon: "/img/integrations/qwen.png" },
        },
        {
          type: "doc",
          id: "tutorials/retool_assist",
          customProps: { icon: "/img/integrations/retool.png" },
        },
        {
          type: "doc",
          id: "tutorials/cost_tracking_coding",
          customProps: { icon: "/img/integrations/litellm.png" },
        },
        { type: "doc", id: "tutorials/claude_code_skills", label: "Manage LiteLLM with AI Agents", customProps: { icon: "/img/integrations/litellm.png" } },
      ]
    },
    {
      type: "category",
      label: "Agent Frameworks & SDKs",
      link: {
        type: "generated-index",
        title: "Agent SDKs",
        description: "Use LiteLLM with agent frameworks and SDKs",
        slug: "/agent_sdks"
      },
      items: [
        { type: "doc", id: "tutorials/openai_agents_sdk", customProps: { icon: "/img/integrations/openai.png" } },
        { type: "doc", id: "tutorials/claude_agent_sdk", customProps: { icon: "/img/integrations/anthropic.png" } },
        { type: "doc", id: "tutorials/copilotkit_sdk", customProps: { icon: "/img/integrations/copilotkit.png" } },
        { type: "doc", id: "tutorials/google_adk", customProps: { icon: "/img/integrations/google.png" } },
        { type: "doc", id: "tutorials/google_genai_sdk", customProps: { icon: "/img/integrations/google.png" } },
        { type: "doc", id: "tutorials/livekit_xai_realtime", customProps: { icon: "/img/integrations/livekit.png" } },
        { type: "doc", id: "integrations/letta", customProps: { icon: "/img/integrations/letta.png" } },
        { type: "doc", id: "tutorials/scalekit_agentkit", label: "Scalekit with LiteLLM", customProps: { icon: "/img/integrations/scalekit.png" } },
        { type: "doc", id: "langchain/langchain", label: "LangChain with LiteLLM", customProps: { icon: "/img/integrations/langchain.png" } },
        { type: "ref", id: "projects/openai-agents", customProps: { icon: "/img/integrations/openai.png" } },
        { type: "doc", id: "tutorials/instructor", label: "Instructor with LiteLLM" },
        { type: "link", label: "Agent Harnesses (litellm.agent)", href: "/docs/harness", className: "sidebar-xlink" },
      ]
    },
    {
      type: "category",
      label: "Observability",
      link: { type: "doc", id: "integrations/observability_index" },
      items: [
        {
          type: "category",
          label: "OpenTelemetry",
          items: [
            "observability/opentelemetry_v2_migration",
            "observability/opentelemetry_v2",
            "observability/opentelemetry_integration",
            "observability/signoz",
          ],
        },
        {
          type: "category",
          label: "LLM observability platforms",
          items: [
            "observability/agentops_integration",
            "observability/argilla",
            "observability/arize_integration",
            "observability/phoenix_integration",
            "observability/athina_integration",
            "observability/braintrust",
            "observability/grafana_cloud",
            "observability/opik_integration",
            "observability/deepeval_integration",
            "observability/helicone_integration",
            "observability/humanloop",
            "observability/langfuse_integration",
            "observability/langsmith_integration",
            "observability/langtrace_integration",
            "observability/levo_integration",
            "observability/literalai_integration",
            "observability/logfire_integration",
            "observability/lunary_integration",
            "observability/mlflow",
            "observability/promptlayer_integration",
            "observability/qualifire_integration",
            "observability/wandb_integration",
          ],
        },
        {
          type: "category",
          label: "Infrastructure backends",
          items: [
            "observability/azure_sentinel",
            "observability/datadog",
            { type: "doc", id: "observability/gcs_bucket_integration", className: "sidebar-enterprise" },
            "observability/newrelic",
            "observability/parseable",
            "observability/posthog_integration",
            "observability/sentry",
            "observability/slack_integration",
            "observability/splunk_observability_cloud",
            "observability/sumologic_integration",
            "observability/supabase_integration",
            "observability/zerobus",
          ],
        },
        {
          type: "category",
          label: "Callbacks and customization",
          items: [
            "observability/callbacks",
            "observability/custom_callback",
            "observability/generic_api",
            "observability/raw_request_response",
            "observability/scrub_data",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Cost & Billing",
      items: [
            "observability/cloudzero",
            "observability/focus",
            "observability/greenscale_integration",
            "observability/lago",
            "observability/mavvrik",
            "observability/openmeter",
            "observability/pointfive",
            "observability/ramp_integration",
            "observability/vantage",
        {
          type: "link",
          label: "Prompt Compression",
          href: "/docs/completion/prompt_compression#server-side-callback-loop-v1messages",
          className: "sidebar-xlink",
        },
        { type: "ref", id: "proxy/headroom" },
      
      ],
    },
    {
      type: "category",
      label: "Guardrails",
      link: {
        type: "generated-index",
        title: "Guardrail Providers",
        description: "Add safety and content filtering to LLM calls",
        slug: "/guardrail_providers"
      },
      items: [
        {
          type: "ref",
          id: "proxy/guardrails/team_based_guardrails",
          label: "Team Bring-Your-Own Guardrails",
        },
        ...[
          { type: "doc", id: "proxy/guardrails/qohash_qostodian_nexus", customProps: { icon: "/img/integrations/qohash.png" } },
          "proxy/guardrails/qualifire",
          { type: "doc", id: "proxy/guardrails/aim_security", customProps: { icon: "/img/integrations/aim-security.png" } },
          "proxy/guardrails/onyx_security",
          { type: "doc", id: "proxy/guardrails/aporia_api", customProps: { icon: "/img/integrations/aporia.png" } },
          { type: "doc", id: "proxy/guardrails/azure_content_guardrail", customProps: { icon: "/img/integrations/azure.png" } },
          { type: "doc", id: "proxy/guardrails/bedrock", customProps: { icon: "/img/integrations/aws.png" } },
          { type: "doc", id: "proxy/guardrails/compresr", customProps: { icon: "/img/integrations/compresr.png" } },
          "proxy/guardrails/typesafe",
          { type: "doc", id: "proxy/guardrails/crowdstrike_aidr", customProps: { icon: "/img/integrations/crowdstrike.png" } },
          { type: "doc", id: "proxy/guardrails/enkryptai", customProps: { icon: "/img/integrations/enkrypt.png" } },
          { type: "doc", id: "proxy/guardrails/ibm_guardrails", customProps: { icon: "/img/integrations/ibm.png" } },
          { type: "doc", id: "proxy/guardrails/grayswan", customProps: { icon: "/img/integrations/grayswan.png" } },
          { type: "doc", id: "proxy/guardrails/hiddenlayer", customProps: { icon: "/img/integrations/hiddenlayer.png" } },
          { type: "doc", id: "proxy/guardrails/lasso_security", customProps: { icon: "/img/integrations/lasso.png" } },
          { type: "doc", id: "proxy/guardrails/guardrails_ai", customProps: { icon: "/img/integrations/guardrails-ai.png" } },
          { type: "doc", id: "proxy/guardrails/lakera_ai", customProps: { icon: "/img/integrations/lakera.png" } },
          { type: "doc", id: "proxy/guardrails/llm_as_a_judge", customProps: { icon: "/img/integrations/litellm.png" } },
          { type: "doc", id: "proxy/guardrails/microsoft_agent_365", customProps: { icon: "/img/integrations/microsoft.png" } },
          { type: "doc", id: "proxy/guardrails/microsoft_purview", customProps: { icon: "/img/integrations/microsoft.png" } },
          { type: "doc", id: "proxy/guardrails/model_armor", customProps: { icon: "/img/integrations/google.png" } },
          { type: "doc", id: "proxy/guardrails/noma_security", customProps: { icon: "/img/integrations/noma.png" } },
          { type: "doc", id: "proxy/guardrails/dynamoai", customProps: { icon: "/img/integrations/dynamoai.png" } },
          { type: "doc", id: "proxy/guardrails/openai_moderation", customProps: { icon: "/img/integrations/openai.png" } },
          { type: "doc", id: "proxy/guardrails/pangea", customProps: { icon: "/img/integrations/pangea.png" } },
          "proxy/guardrails/pillar_security",
          { type: "doc", id: "proxy/guardrails/repelloai", customProps: { icon: "/img/integrations/repello.png" } },
          { type: "doc", id: "proxy/guardrails/promptguard", customProps: { icon: "/img/integrations/prompt-security.png" } },
          { type: "doc", id: "proxy/guardrails/pii_masking_v2", customProps: { icon: "/img/integrations/microsoft.png" } },
          { type: "doc", id: "proxy/guardrails/panw_prisma_airs", customProps: { icon: "/img/integrations/panw.png" } },
          { type: "doc", id: "proxy/guardrails/secret_detection", customProps: { icon: "/img/integrations/litellm.png" } },
          { type: "doc", id: "proxy/guardrails/sensitive_data_routing", customProps: { icon: "/img/integrations/litellm.png" } },
          { type: "doc", id: "proxy/guardrails/custom_guardrail", customProps: { icon: "/img/integrations/litellm.png" } },
          { type: "doc", id: "proxy/guardrails/custom_code_guardrail", customProps: { icon: "/img/integrations/litellm.png" } },
          { type: "doc", id: "proxy/guardrails/prompt_injection", customProps: { icon: "/img/integrations/litellm.png" } },
          { type: "doc", id: "proxy/guardrails/tool_permission", customProps: { icon: "/img/integrations/litellm.png" } },
          { type: "doc", id: "proxy/guardrails/rubrik", customProps: { icon: "/img/integrations/rubrik.png" } },
          { type: "doc", id: "proxy/guardrails/zscaler_ai_guard", customProps: { icon: "/img/integrations/zscaler.png" } },
          { type: "doc", id: "proxy/guardrails/javelin", customProps: { icon: "/img/integrations/javelin.png" } },
          { type: "doc", id: "proxy/guardrails/akto", customProps: { icon: "/img/integrations/akto.png" } },
          "proxy/guardrails/vigil_guard",
          { type: "doc", id: "proxy/guardrails/xecguard", customProps: { icon: "/img/integrations/xecguard.png" } },
          { type: "doc", id: "proxy/guardrails/straiker", customProps: { icon: "/img/integrations/straiker.png" } },
          "proxy/guardrails/alice",
          "proxy/guardrails/llm_shield_proxy",
          { type: "doc", id: "proxy/guardrails/conduct", customProps: { icon: "/img/integrations/conduct.png" } },
        ].sort((a, b) => (typeof a === "string" ? a : a.id).localeCompare(typeof b === "string" ? b : b.id)),
      ],
    },
    {
      type: "category",
      label: "Alerting & Monitoring",
      items: [
        "proxy/alerting",
        { type: "doc", id: "proxy/pagerduty", className: "sidebar-enterprise" },
        "proxy/prometheus",
        "proxy/pyroscope_profiling"
      ]
    },
    {
      type: "category",
      label: "Prompt Management (Beta)",
      items: [
        "proxy/litellm_prompt_management",
        "proxy/custom_prompt_management",
        "proxy/native_litellm_prompt",
        "proxy/prompt_management",
        "proxy/arize_phoenix_prompts"
      ]
    },
    {
      type: "category",
      label: "Build an Integration",
      items: [
        { type: "doc", id: "integrations/community", label: "Community integrations" },
        {
          type: "category",
          label: "Contributing to Integrations",
          items: [
            {
              type: "autogenerated",
              dirName: "contribute_integration"
            }
          ],
        },
        {
          type: "category",
          label: "Contributing to Guardrails",
          items: [
            { type: "ref", id: "adding_provider/generic_guardrail_api" },
            { type: "ref", id: "adding_provider/simple_guardrail_tutorial" },
            { type: "ref", id: "adding_provider/adding_guardrail_support" },
          ]
        },
        {
          type: "category",
          label: "Contributing to Prompt Management",
          items: [
            "adding_provider/generic_prompt_management_api",
          ]
        },
      ],
    },
    { type: "link", label: "Model Providers", href: "/docs/providers", className: "sidebar-xlink" },
  ],
  // But you can create a sidebar manually
  tutorialSidebar: [
    // ════════════════════════════════════════════════════════════
    // GET STARTED
    // ════════════════════════════════════════════════════════════
    { type: "html", value: "Get started", className: "sidebar-caption", defaultStyle: true },
    { type: "doc", id: "index", label: "Quickstart" },
    { type: "doc", id: "agent_resources", label: "Agent resources" },

    // ════════════════════════════════════════════════════════════
    // AI GATEWAY
    // Set-up groups follow the order a new deployment goes through:
    // Deploy → Configuration → Models & Providers → Client Setup → Authentication → Spend & Budgets.
    // Add new pages inside one of these groups, or in the groups after them.
    // ════════════════════════════════════════════════════════════
    { type: "html", value: "Products", className: "sidebar-caption", defaultStyle: true },
    {
      type: "category",
      label: "AI Gateway",
      link: { type: "doc", id: "gateway_overview" },
      items: [
        { type: "doc", id: "proxy/docker_quick_start", label: "Quickstart" },
        { type: "doc", id: "proxy/quick_start", label: "CLI Quickstart" },
        { type: "doc", id: "benchmarks", label: "Benchmarks" },
        { type: "html", value: "Set up", className: "sidebar-group-label", defaultStyle: true },
        {
          type: "category",
          label: "Deploy",
          items: [
            "proxy/deploy",
            "proxy/prod",
            "proxy/health",
            {
              type: "category",
              label: "Sizing & Scaling",
              items: [
                "proxy/redis_requirements",
                "proxy/db_sizing",
                "proxy/redis_sizing",
                "proxy/server_tuning",
                "proxy/high_throughput",
                "proxy/db_read_replica",
                { type: "doc", id: "proxy/multi_region", className: "sidebar-enterprise" },
                { type: "doc", id: "proxy/global_control_plane", className: "sidebar-enterprise" },
                "proxy/manifests_to_microservices",
              ],
            },
            {
              type: "category",
              label: "Secret Managers",
              items: [
                { type: "doc", id: "secret_managers/overview", className: "sidebar-enterprise" },
                "secret_managers/aws_secret_manager",
                "secret_managers/aws_kms",
                "secret_managers/azure_key_vault",
                "secret_managers/cyberark",
                "secret_managers/google_secret_manager",
                "secret_managers/google_kms",
                "secret_managers/hashicorp_vault",
                "secret_managers/custom_secret_manager",
              ],
            },
            "proxy/security_best_practices",
            "proxy/security_owasp_llm_top10",
            "proxy/rust_gateway",
          ],
        },
        {
          type: "category",
          label: "Configuration",
          items: [
            { type: "doc", id: "proxy/configs", label: "Config.yaml" },
            "proxy/config_settings",
            "proxy/config_management",
            "proxy/cli",
            "guides/security_settings",
          ],
        },
        {
          type: "category",
          label: "Models & Providers",
          items: [
            "proxy/model_management",
            "proxy/model_access_guide",
            "proxy/model_access",
            "proxy/model_access_groups",
            "proxy/access_groups",
            { type: "doc", id: "proxy/team_model_add", className: "sidebar-enterprise" },
            "proxy/credential_routing",
            { type: "link", label: "All Providers", href: "/docs/providers", className: "sidebar-xlink" },
          ],
        },
        {
          type: "category",
          label: "Client Setup",
          items: [
            "proxy/client_setup/overview",
            "proxy/client_setup/claude_code",
            "proxy/client_setup/claude_desktop",
            "proxy/client_setup/codex_chatgpt_desktop",
            "proxy/client_setup/codex_cli",
            "proxy/user_keys",
            "proxy/request_headers",
            "proxy/response_headers",
            "proxy/forward_client_headers",
            "proxy/clientside_auth",
            "proxy/model_discovery",
            {
              type: "category",
              label: "Enterprise sign-in and billing",
              items: [
                { type: "ref", id: "tutorials/claude_code_gateway", label: "Claude Code Gateway", className: "sidebar-xlink" },
                { type: "ref", id: "tutorials/claude_desktop_cowork", label: "Claude Desktop Cowork", className: "sidebar-xlink" },
                { type: "ref", id: "proxy/cli_sso", label: "CLI SSO", className: "sidebar-xlink" },
                { type: "ref", id: "tutorials/claude_code_okta_sso", label: "Claude Code Okta SSO", className: "sidebar-xlink" },
                { type: "ref", id: "tutorials/claude_code_byok", label: "Claude Code BYOK", className: "sidebar-xlink" },
                { type: "ref", id: "tutorials/claude_code_max_subscription", label: "Claude Code Max Subscription", className: "sidebar-xlink" },
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Authentication & Access",
          items: [
            { type: "html", value: "Essential", className: "sidebar-group-label", defaultStyle: true },
            "proxy/virtual_keys",
            "proxy/access_control",
            {
              type: "category",
              label: "Single Sign-On",
              items: [
                { type: "doc", id: "proxy/admin_ui_sso", className: "sidebar-enterprise" },
                { type: "doc", id: "proxy/saml_sso", className: "sidebar-enterprise" },
                { type: "doc", id: "proxy/custom_sso", className: "sidebar-enterprise" },
                { type: "doc", id: "tutorials/scim_litellm", className: "sidebar-enterprise" },
                "proxy/cli_sso",
              ],
            },
            { type: "html", value: "Advanced", className: "sidebar-group-label", defaultStyle: true },
            { type: "doc", id: "proxy/token_auth", className: "sidebar-enterprise" },
            { type: "doc", id: "proxy/jwt_key_mapping", className: "sidebar-enterprise" },
            { type: "doc", id: "proxy/oauth2", label: "OAuth 2.0 Authentication", className: "sidebar-enterprise" },
            "proxy/jwt_auth_arch",
            "oidc",
            {
              type: "doc",
              id: "proxy/identity_provisioning",
              label: "Provisioning & Keys",
            },
            "proxy/service_accounts",
            "proxy/custom_auth",
            { type: "doc", id: "proxy/ip_address", className: "sidebar-enterprise" },
            { type: "doc", id: "proxy/public_routes", className: "sidebar-enterprise" },
            "proxy/master_key_rotations",
            { type: "ref", id: "proxy/multiple_admins", label: "Audit Logs", className: "sidebar-enterprise" },
          ],
        },
        {
          type: "category",
          label: "Spend Tracking",
          items: [
            { type: "html", value: "Essential", className: "sidebar-group-label", defaultStyle: true },
            "proxy/cost_tracking",
            "proxy/request_tags",
            "proxy/billing",
            "proxy/custom_pricing",
            { type: "html", value: "Advanced", className: "sidebar-group-label", defaultStyle: true },
            "proxy/spend_capture_rate",
            { type: "doc", id: "proxy/billing_metrics", className: "sidebar-enterprise" },
            "proxy/custom_model_cost_map",
            "proxy/ptu_flat_cost",
            "proxy/pricing_calculator",
            "proxy/provider_margins",
            "proxy/provider_discounts",
            "proxy/off_peak_pricing",
            "proxy/sync_models_github",
            "tutorials/vertex_ai_pay_go",
            "proxy/spend_logs_deletion",
          ],
        },
        {
          type: "category",
          label: "Budgets & Rate Limits",
          items: [
            { type: "html", value: "Essential", className: "sidebar-group-label", defaultStyle: true },
            "proxy/users",
            "proxy/team_budgets",
            { type: "doc", id: "proxy/project_management", className: "sidebar-enterprise" },
            "proxy/customers",
            { type: "html", value: "Advanced", className: "sidebar-group-label", defaultStyle: true },

            { type: "doc", id: "proxy/ui_team_soft_budget_alerts", className: "sidebar-enterprise" },
            "proxy/tag_budgets",
            "proxy/model_access_group_budgets",
            "proxy/dynamic_rate_limit",
            "proxy/io_token_rate_limits",
            { type: "doc", id: "proxy/rate_limit_tiers", className: "sidebar-enterprise" },
            { type: "doc", id: "proxy/temporary_budget_increase", className: "sidebar-enterprise" },
            "proxy/budget_reset_and_tz",
            "proxy/budget_fallbacks",
          ],
        },
        // Enterprise pages live in enterpriseSidebar (the Enterprise tab). This ref is a door into it.
        { type: "ref", id: "enterprise", label: "Enterprise" },
        { type: "html", value: "Routing & cost", className: "sidebar-group-label", defaultStyle: true },
        {
          type: "category",
          label: "Load Balancing & Routing",
          link: { type: "doc", id: "proxy/load_balancing" },
          items: [
            { type: "html", value: "Load balancing", className: "sidebar-group-label", defaultStyle: true },
            "routing",
            "wildcard_routing",
            "proxy/health_check_routing",
            "scheduler",
            { type: "html", value: "Fallbacks & timeouts", className: "sidebar-group-label", defaultStyle: true },
            "proxy/reliability",
            "proxy/timeout",
            "proxy/fallback_management",
            { type: "html", value: "Routing rules", className: "sidebar-group-label", defaultStyle: true },
            "proxy/tag_routing",
            "proxy/provider_budget_routing",
            "proxy/keys_teams_router_settings",
            "proxy/ui/routing_groups",
            "routing_plugins",
            "fusion",
          ],
        },
        "traffic_mirroring",
        {
          type: "category",
          label: "Caching",
          link: { type: "doc", id: "proxy/caching" },
          items: [
            "proxy/caching_redis",
            "proxy/elasticache_iam",
            "proxy/gcp_memorystore_iam",
            "proxy/azure_redis_ad",
            "proxy/caching_semantic",
            "proxy/caching_object_storage",
            "proxy/caching_controls",
            "proxy/caching_settings",
          ],
        },
        {
          type: "category",
          label: "Cost Optimization",
          items: [
            {
              type: "link",
              label: "Prompt Compression",
              href: "/docs/completion/prompt_compression#server-side-callback-loop-v1messages",
              className: "sidebar-xlink",
            },
            "proxy/headroom",
          ],
        },
        { type: "html", value: "Safety", className: "sidebar-group-label", defaultStyle: true },
        {
          type: "category",
          label: "Guardrails",
          items: [
            "proxy/guardrails/quick_start",
            "proxy/guardrails/team_based_guardrails",
            "proxy/guardrails/guardrail_load_balancing",
            "proxy/guardrails/test_playground",
            "proxy/guardrails/litellm_content_filter",
            "proxy/guardrails/realtime_guardrails",
            "proxy/guardrails/batch_guardrails",
            {
              type: "link",
              label: "Guardrail Providers",
              href: "/docs/guardrail_providers",
              className: "sidebar-xlink",
            },
            {
              type: "category",
              label: "Contributing to Guardrails",
              items: [
                "adding_provider/generic_guardrail_api",
                "adding_provider/simple_guardrail_tutorial",
                "adding_provider/adding_guardrail_support",
              ]
            },
          ],
        },
        {
          type: "category",
          label: "Policies",
          items: [
            "proxy/guardrails/guardrail_policies",
            "proxy/guardrails/policy_flow_builder",
            "proxy/guardrails/policy_templates",
            "proxy/guardrails/policy_tags",
          ],
        },
        { type: "html", value: "Observability", className: "sidebar-group-label", defaultStyle: true },
        {
          type: "category",
          label: "Logging, Alerting, Metrics",
          items: [
            { type: "doc", id: "proxy/dynamic_logging", className: "sidebar-enterprise" },
            "proxy/logging",
            "proxy/logging_spec",
            { type: "doc", id: "proxy/team_logging", className: "sidebar-enterprise" },
            "proxy/email",
          ],
        },
        { type: "html", value: "Manage", className: "sidebar-group-label", defaultStyle: true },
        {
          type: "category",
          label: "Admin UI",
          items: [
            "proxy/ui",
            {
              type: "category",
              label: "Setup & Customization",
              items: [
                "proxy/ui/ui_edit_logo",
                "proxy/custom_root_ui",
                "proxy/plugins",
              ]
            },
            {
              type: "category",
              label: "Models",
              items: [
                "proxy/ai_hub",
                "proxy/model_compare_ui",
              ]
            },
            {
              type: "category",
              label: "Teams & Organizations",
              items: [
                { type: "ref", id: "proxy/access_control", label: "Role-based Access Controls (RBAC)", className: "sidebar-xlink" },
                "proxy/self_serve",
                "proxy/public_teams",
                "proxy/ui_project_management",
                "proxy/ui_search_tools",
                "proxy/ui/bulk_edit_users",
                "proxy/ui/page_visibility",
              ]
            },
            {
              type: "category",
              label: "Observability: Usage",
              items: [
                "proxy/customer_usage",
                "proxy/endpoint_activity",
              ]
            },
            {
              type: "category",
              label: "Logs",
              items: [
                "proxy/ui_logs",
                "proxy/ui_spend_log_settings",
                "proxy/ui_logs_sessions",
                "proxy/deleted_keys_teams",
              ]
            },
            "proxy/ui/chat_ui",
          ],
        },
        {
          type: "category",
          label: "LiteAdmin",
          items: [
            "proxy/liteadmin_mcp",
            "proxy/liteadmin_mcp_enterprise",
            "proxy/liteadmin_slack",
          ],
        },
        {
          type: "category",
          label: "Create Custom Plugins",
          description: "Modify requests, responses, and more",
          items: [
            "proxy/call_hooks",
            "proxy/agentic_loop_hook",
            "proxy/rules",
            "proxy/worker_startup_hooks",
            "extras/creating_adapters",
          ]
        },
        "proxy/memory",
        { type: "html", value: "Architecture & help", className: "sidebar-group-label", defaultStyle: true },
        {
          type: "category",
          label: "Architecture",
          items: [
            "proxy/architecture",
            "proxy/multi_tenant_architecture",
            "proxy/user_management_heirarchy",
            "proxy/key_auth_arch",
            "proxy/db_info",
          ],
        },
        {
          type: "link",
          label: "All Endpoints (Swagger)",
          href: "https://docs.litellm.ai/api-reference/",
        },
        {
          type: "category",
          label: "Troubleshooting",
          items: ["proxy/debugging", "proxy/error_reference", "proxy/error_diagnosis"],
        },
      ],
    },
    {
      type: "category",
      label: "Python SDK",
      link: { type: "doc", id: "python_sdk" },
      items: [
        { type: "doc", id: "learn/sdk_quickstart", label: "Quickstart" },
        { type: "doc", id: "litellm_core", label: "LiteLLM Core" },
        {
          type: "category",
          label: "SDK Functions",
          items: [
            {
              type: "doc",
              id: "completion/input",
              label: "completion()",
            },
            {
              type: "doc",
              id: "embedding/supported_embedding",
              label: "embedding()",
            },
            {
              type: "doc",
              id: "response_api",
              label: "responses()",
            },
            {
              type: "doc",
              id: "text_completion",
              label: "text_completion()",
            },
            {
              type: "doc",
              id: "image_generation",
              label: "image_generation()",
            },
            {
              type: "doc",
              id: "completion/prompt_compression",
              label: "compress()",
            },
            {
              type: "doc",
              id: "audio_transcription",
              label: "transcription()",
            },
            {
              type: "doc",
              id: "text_to_speech",
              label: "speech()",
            },
            {
              type: "doc",
              id: "sandbox",
              label: "acode_interpreter_tool()",
            },
            {
              type: "link",
              label: "All Supported Endpoints",
              href: "/docs/supported_endpoints",
              className: "sidebar-xlink",
            },
          ],
        },
        // litellm.agent(): agent harnesses (Claude Code, Codex, OpenCode, Deep Agents, Tool Loop).
        // Styled by the "litellm.harness docs" block in src/css/custom.css.
        {
          type: "category",
          label: "Agent Harnesses",
          className: "harness-sidebar",
          items: [
            {
              type: "category",
              label: "Getting started",
              className: "harness-group",
              collapsible: false,
              items: [
                { type: "doc", id: "harness/index", label: "Overview" },
                { type: "doc", id: "harness/gateway", label: "Using with AI Gateway" },
              ],
            },
            {
              type: "category",
              label: "Harnesses",
              className: "harness-group",
              collapsible: false,
              items: [
                "harness/supported",
                "harness/claude_code",
                "harness/codex",
                "harness/opencode",
                "harness/deepagents",
                "harness/tool_loop",
              ],
            },
            {
              type: "category",
              label: "Guides",
              className: "harness-group",
              collapsible: false,
              items: [
                "harness/quickstart",
                "harness/models",
                "harness/sessions",
                "harness/events",
                "harness/sandboxes",
                "harness/tools",
                "harness/permissions",
                "harness/structured_output",
              ],
            },
            {
              type: "category",
              label: "Reference",
              className: "harness-group",
              collapsible: false,
              items: ["harness/api_reference", "harness/errors"],
            },
          ],
        },
        {
          type: "category",
          label: "Configuration",
          items: [
            "set_keys",
            "proxy_auth",
            "caching/all_caches",
          ],
        },
        "completion/token_usage",
        { type: "html", value: "Utilities", className: "sidebar-group-label", defaultStyle: true },
        "completion/message_trimming",
        "completion/model_alias",
        "completion/prompt_formatting",
        { type: "html", value: "Reliability & testing", className: "sidebar-group-label", defaultStyle: true },
        "completion/reliable_completions",
        "completion/mock_requests",
        "exception_mapping",
      ],
    },
    {
      type: "category",
      label: "MCP Gateway",
      link: { type: "doc", id: "mcp" },
      items: [
        { type: "doc", id: "mcp_usage", label: "Quickstart" },
        { type: "doc", id: "mcp_deployment", label: "Deployment" },
        {
          type: "category",
          label: "MCP Servers",
          items: [
            "mcp_servers/index",
            "mcp_servers/slack",
            "mcp_servers/atlassian",
            "mcp_servers/linear",
            "mcp_servers/microsoft_365",
            "mcp_openapi",
            "mcp_toolsets",
            "mcp_server_submissions",
          ],
        },
        {
          type: "category",
          label: "Authentication",
          items: [
            "mcp_authentication",
            "mcp_oauth",
            "mcp_per_user_auth",
            "mcp_oauth_passthrough",
            "mcp_obo_auth",
            "mcp_id_jag",
            "mcp_aws_sigv4",
            "mcp_zero_trust",
            { type: "doc", id: "auth_overview", label: "Gateway Auth Reference" },
          ],
        },
        {
          type: "category",
          label: "Access Control",
          items: [
            "mcp_control",
            "mcp_grant_access",
            "mcp_client_allowlist",
            "mcp_public_internet",
            "proxy/tool_policies",
          ],
        },
        {
          type: "category",
          label: "Features",
          items: [
            { type: "html", value: "Essential", className: "sidebar-group-label", defaultStyle: true },
            "mcp_cost",
            "mcp_guardrail",
            "mcp_tool_search",
            "mcp_rest_api",
            { type: "html", value: "Advanced", className: "sidebar-group-label", defaultStyle: true },
            "mcp_semantic_filter",
          ],
        },
        { type: "doc", id: "mcp_config_reference", label: "Configuration Reference" },
        { type: "doc", id: "mcp_troubleshoot", label: "Troubleshooting & FAQ" },
      ],
    },
    {
      type: "category",
      label: "Agent Gateway",
      link: { type: "doc", id: "a2a" },
      items: [
        { type: "doc", id: "a2a_invoking_agents", label: "Quickstart" },
        { type: "html", value: "Essential", className: "sidebar-group-label", defaultStyle: true },
        "a2a_agent_card",
        "a2a_agent_headers",
        "a2a_agent_permissions",
        "a2a_cost_tracking",
        { type: "html", value: "Advanced", className: "sidebar-group-label", defaultStyle: true },
        "a2a_iteration_budgets",
        "a2a_kill_switch",
        "skills_gateway",
      ],
    },
    {
      type: "category",
      label: "Auto Router",
      link: { type: "doc", id: "auto_router/index" },
      items: [
        "auto_router/setup",
        "auto_router/optimize_classifier",
        "auto_router/decision_classifiers",
        "auto_router/user_setup",
        "auto_router/recommended_configurations",
        "auto_router/benchmarks",
        "auto_router/prompt_caching",
        "auto_router/evaluate",
        "auto_router/telemetry",
        "auto_router/feature_history",
        { type: "html", value: "Configuration", className: "sidebar-group-label", defaultStyle: true },
        "proxy/auto_routing",
        "proxy/auto_routing_semantic",
        "proxy/auto_routing_benchmark",
        "adaptive_router",
        { type: "link", label: "Claude Code and Claude Desktop", href: "/docs/tutorials/claude_code_autorouter", className: "sidebar-xlink" },
        { type: "link", label: "Prompt Cache Routing", href: "/docs/tutorials/claude_code_prompt_cache_routing", className: "sidebar-xlink" },
      ],
    },
    require('./docs/proxy/lens/sidebar'),
    { type: "html", value: "Features", className: "sidebar-caption", defaultStyle: true },
    { type: "doc", id: "guides/index", className: "top-level-doc-item" },
    {
      type: "category",
      label: "Requests & Responses",
      link: {
        type: "generated-index",
        title: "Requests & Responses",
        description: "Streaming, batching, structured outputs, and reasoning.",
        slug: "/guides/core_request_response_patterns",
      },
      items: [
        "completion/stream",
        "completion/batching",
        "completion/json_mode",
        "reasoning_content",
      ],
    },
    {
      type: "category",
      label: "Tool Calling",
      link: {
        type: "generated-index",
        title: "Tool Calling",
        description: "Function calling, web search and fetch, computer use, code interpreter, and knowledge bases.",
        slug: "/guides/tools_integrations",
      },
      items: [
        "completion/function_call",
        "completion/web_search",
        "integrations/websearch_interception",
        "completion/web_fetch",
        "completion/computer_use",
        "guides/code_interpreter",
        "completion/anthropic_advisor_tool",
        "completion/knowledgebase",
      ],
    },
    {
      type: "category",
      label: "Multimodal",
      link: {
        type: "generated-index",
        title: "Multimodal",
        description: "Vision, audio, PDF input, and image generation in chat.",
        slug: "/guides/multimodal_io",
      },
      items: [
        "completion/vision",
        "completion/audio",
        "completion/document_understanding",
        "completion/image_generation_chat",
      ],
    },
    {
      type: "category",
      label: "Prompts & Context",
      link: {
        type: "generated-index",
        title: "Prompts & Context",
        description: "Prompt caching, assistant prefill, and predicted outputs.",
        slug: "/guides/prompts_context",
      },
      items: [
        "completion/prompt_caching",
        "completion/prefix",
        "completion/predict_outputs",
      ],
    },
    {
      type: "category",
      label: "Compatibility",
      link: {
        type: "generated-index",
        title: "Compatibility",
        description: "Provider-specific params, unsupported params, and message sanitization.",
        slug: "/guides/compatibility_extensibility",
      },
      items: [
        "completion/provider_specific_params",
        "completion/drop_params",
        "completion/message_sanitization",
      ],
    },
    { type: "html", value: "Developer Tools", className: "sidebar-caption", defaultStyle: true },
    { type: "doc", id: "liteagents", label: "liteagents SDK", className: "top-level-doc-item sidebar-beta" },
    {
      type: "category",
      label: "lite CLI",
      link: { type: "doc", id: "proxy/management_cli" },
      items: [
        { type: "doc", id: "learn/autorouter_cli", label: "lite autoroute", className: "sidebar-preview" },
      ],
    },
    {
      type: "category",
      label: "Self-Hosted Coding Agents",
      link: {
        type: "generated-index",
        title: "Self-Hosted Coding Agents",
        description: "Run coding agents on your own infrastructure, with LiteLLM as the model gateway",
        slug: "/self_hosted_coding_agents"
      },
      items: [
        {
          type: "category",
          label: "Moyai",
          link: {type: "doc", id: "self_hosted_coding_agents/moyai"},
          items: [
            "self_hosted_coding_agents/moyai/setup",
            "self_hosted_coding_agents/moyai/architecture",
          ],
        },
      ]
    },
    { type: "html", value: "Reference", className: "sidebar-caption", defaultStyle: true },
    {
      type: "category",
      label: "Supported Endpoints",
      link: {
        type: "generated-index",
        title: "Supported Endpoints",
        description:
          "Learn how to deploy + call models from different providers on LiteLLM",
        slug: "/supported_endpoints",
      },
      items: [
        "assistants",
        { type: "ref", id: "audio_transcription" },
        { type: "ref", id: "text_to_speech" },
        {
          type: "category",
          label: "/batches",
          items: [
            "batches",
            "proxy/managed_batches",
            "proxy/unmanaged_vertex_batches",
          ]
        },
        "containers",
        "container_files",
        {
          type: "category",
          label: "/chat/completions",
          link: {
            type: "generated-index",
            title: "Chat Completions",
            description: "Details on the completion() function",
            slug: "/completion",
          },
          items: [
            { type: "ref", id: "completion/input" },
            "completion/output",
            "completion/usage",
            "completion/http_handler_config",
          ],
        },
        { type: "ref", id: "text_completion" },
        "bedrock_converse",
        { type: "ref", id: "embedding/supported_embedding" },
        {
          type: "category",
          label: "/files",
          items: [
            "files_endpoints",
            "proxy/litellm_managed_files",
          ],
        },
        {
          type: "category",
          label: "/fine_tuning",
          items: [
            "fine_tuning",
            "proxy/managed_finetuning",
          ]
        },
        "evals_api",
        "generateContent",
        "apply_guardrail",
        "bedrock_invoke",
        "interactions",
        "managed_agents",
        "memory_management",
        "image_edits",
        { type: "ref", id: "image_generation" },
        "image_variations",
        "videos",
        "proxy/veo_video_generation",
        {
          type: "category",
          label: "/vector_stores - Vector Stores",
          items: [
            "vector_stores/index",
            "vector_stores/managed_vector_stores",
            "vector_stores/create",
            "vector_stores/search",
            "vector_store_files",
            "rag_ingest",
            "rag_query",
          ]
        },
        {
          type: "category",
          label: "/v1/messages",
          items: [
            "anthropic_unified/index",
            "anthropic_unified/structured_output",
            "anthropic_unified/messages_to_responses_mapping",
            "anthropic_unified/native_passthrough",
          ]
        },
        "count_tokens",
        "anthropic_count_tokens",
        "decisions",
        "moderation",
        "ocr",
        {
          type: "category",
          label: "Pass-through Endpoints (Anthropic SDK, etc.)",
          items: [
            "pass_through/intro",
            "pass_through/anthropic_completion",
            "pass_through/assembly_ai",
            "pass_through/bedrock",
            "pass_through/azure_passthrough",
            "pass_through/azure_speech",
            "pass_through/cohere",
            "pass_through/comprehend_medical",
            "pass_through/cursor",
            "pass_through/deepgram_listen_websocket",
            "pass_through/gigachat",
            "pass_through/google_ai_studio",
            "pass_through/langfuse",
            "pass_through/mistral",
            "pass_through/openai_passthrough",
            "pass_through/tinyfish",
            "pass_through/transcribe",
            "pass_through/typesafe",
            "proxy/passthrough_managed_ids",
            {
              type: "category",
              label: "Vertex AI",
              items: [
                "pass_through/vertex_ai",
                "pass_through/vertex_ai_live_websocket",
                "pass_through/vertex_ai_search_datastores",
              ]
            },
            "pass_through/vllm",
            "proxy/pass_through",
            "proxy/pass_through_cost_tracking",
            "proxy/pass_through_guardrails"
          ]
        },
        "realtime",
        "proxy/realtime_webrtc",
        "rerank",
        { type: "ref", id: "response_api" },
        "prompt_management",
        "response_api_compact",
        {
          type: "category",
          label: "/search",
          items: [
            "search/index",
            "search/perplexity",
            "search/tavily",
            "search/exa_ai",
            "search/brave",
            "search/parallel_ai",
            "search/google_pse",
            "search/dataforseo",
            "search/firecrawl",
            "search/searxng",
            "search/linkup",
            "search/serper",
            "search/you_com",
            "search/apiserpent",
            "search/agentcore",
            "search/nimble",
            "search/bing_grounding",
          ]
        },
        "skills",

      ],
    },
    {
      type: "category",
      label: "Providers",
      link: {
        type: "generated-index",
        title: "Providers",
        description:
          "Learn how to deploy + call models from different providers on LiteLLM",
        slug: "/providers",
      },
      items: [
        { type: "link", label: "Models & Pricing", href: "https://models.litellm.ai" },
        "guides/finetuned_models",
        { type: "category", label: "Popular", items: [
          { type: "category", label: "OpenAI", items: [
            "providers/openai",
            "providers/openai/responses_api",
            "providers/openai/text_to_speech",
            "providers/openai/videos",
            "providers/openai/ultrafast",
            "providers/text_completion_openai",
          ] },
          { type: "category", label: "Anthropic", items: [
            "providers/anthropic",
            "providers/anthropic_tool_search",
            "providers/anthropic_preserved_thinking",
          ] },
          { type: "category", label: "Google AI Studio", items: [
            "providers/gemini",
            "providers/gemini/videos",
            "providers/gemini/music",
            "providers/gemini_file_search",
            "providers/google_ai_studio/files",
            "providers/google_ai_studio/image_gen",
            "providers/google_ai_studio/realtime",
          ] },
          { type: "category", label: "Vertex AI", items: [
            "providers/vertex",
            "providers/vertex_ai/videos",
            "providers/vertex_partner",
            "providers/vertex_self_deployed",
            "providers/vertex_embedding",
            "providers/vertex_image",
            "providers/vertex_speech",
            "providers/vertex_transcription",
            "providers/vertex_batch",
            "providers/vertex_ocr",
            "providers/vertex_ai_agent_engine",
            "providers/vertex_realtime",
          ] },
          { type: "category", label: "Azure OpenAI", items: [
            "providers/azure/azure",
            "providers/azure/azure_responses",
            "providers/azure/azure_embedding",
            "providers/azure/azure_speech",
            "providers/azure/videos",
          ] },
          { type: "category", label: "Azure AI", items: [
            "providers/azure_ai",
            "providers/azure_ai/azure_model_router",
            "providers/azure_ai_agents",
            "providers/azure_ocr",
            "providers/azure_document_intelligence",
            "providers/azure_ai_speech",
            "providers/azure_ai_img",
            "providers/azure_ai_vector_stores",
            "providers/azure_ai/azure_ai_vector_stores_passthrough",
          ] },
          { type: "category", label: "Bedrock", items: [
            "providers/bedrock",
            "providers/bedrock_embedding",
            "providers/bedrock_imported",
            "providers/bedrock_image_gen",
            "providers/bedrock_rerank",
            "providers/bedrock_agentcore",
            "providers/bedrock_agents",
            "providers/bedrock_writer",
            "providers/bedrock_batches",
            "providers/bedrock_realtime_with_audio",
            "providers/aws_polly",
            "providers/bedrock_vector_store",
            "providers/bedrock_mantle",
          ] },
          { type: "category", label: "Mistral AI", items: [
            "providers/mistral",
            "providers/mistral_batches",
          ] },
          { type: "category", label: "xAI", items: [
            "providers/xai",
            "providers/xai_realtime",
            "providers/xai_batches",
          ] },
          "providers/deepseek",
          "providers/groq",
        ] },
        { type: "category", label: "Self-Hosted & Local", items: [
          "providers/ollama",
          { type: "category", label: "vLLM", items: [
            "providers/vllm",
            "providers/vllm_batches",
          ] },
          "providers/lm_studio",
          "providers/llamafile",
          "providers/docker_model_runner",
          "providers/lemonade",
          "providers/triton-inference-server",
          "providers/xinference",
          "providers/infinity",
          { type: "category", label: "Nvidia NIM", items: [
            "providers/nvidia_nim",
            "providers/nvidia_nim_rerank",
          ] },
          "providers/petals",
          "providers/custom_llm_server",
        ] },
        { type: "category", label: "Gateways & OpenAI-Compatible", items: [
          "providers/openai_compatible",
          "providers/litellm_proxy",
          "providers/openrouter",
          "providers/vercel_ai_gateway",
          "providers/helicone",
          "providers/cometapi",
          "providers/clf_ai_gateway",
          "providers/poe",
        ] },
        { type: "category", label: "Vector Stores", items: [
          "providers/milvus_vector_stores",
          "providers/mongodb_vector_stores",
          "providers/s3_vectors",
          "providers/valkey_vector_stores",
          "providers/ragflow_vector_store",
        ] },
        { type: "category", label: "Agent Providers", items: [
          "providers/langgraph",
          "providers/pydantic_ai_agent",
        ] },
        { type: "category", label: "All Providers A-Z", items: [
          "providers/abliteration",
          "providers/ai21",
          "providers/aiml",
          "providers/aleph_alpha",
          "providers/amazon_nova",
          "providers/anyscale",
          "providers/apertis",
          "providers/aws_sagemaker",
          "providers/baseten",
          "providers/black_forest_labs",
          "providers/black_forest_labs_img_edit",
          "providers/bytez",
          "providers/cerebras",
          "providers/chatgpt",
          "providers/chutes",
          "providers/clarifai",
          "providers/cloudflare_workers",
          "providers/codestral",
          "providers/cognition",
          "providers/cohere",
          "providers/compactifai",
          "providers/coralbricks",
          "providers/crusoe",
          "providers/dashscope",
          "providers/databricks",
          "providers/datarobot",
          "providers/deepgram",
          "providers/deepinfra",
          "providers/edenai",
          "providers/elevenlabs",
          "providers/empiriolabs",
          "providers/fal_ai",
          "providers/featherless_ai",
          "providers/fireworks_ai",
          "providers/friendliai",
          "providers/galadriel",
          "providers/github",
          "providers/github_copilot",
          "providers/gmi",
          "providers/gradient_ai",
          "providers/heroku",
          { type: "category", label: "HuggingFace", items: [
            "providers/huggingface",
            "providers/huggingface_rerank",
          ] },
          "providers/hyperbolic",
          "providers/inception",
          "providers/jina_ai",
          "providers/lambda_ai",
          "providers/llamagate",
          "providers/manus",
          "providers/meta",
          "providers/meta_llama",
          "providers/microsoft_365_copilot",
          "providers/minimax",
          "providers/moonshot",
          "providers/morph",
          "providers/nadir",
          "providers/nano-gpt",
          "providers/nebius",
          "providers/nlp_cloud",
          "providers/novita",
          { type: "doc", id: "providers/nscale", label: "Nscale (EU Sovereign)" },
          "providers/nvidia_riva",
          "providers/oci",
          "providers/ovhcloud",
          { type: "category", label: "Perplexity AI", items: [
            "providers/perplexity",
            "providers/perplexity_embedding",
          ] },
          "providers/predibase",
          "providers/prism",
          "providers/publicai",
          "providers/qwencloud",
          "providers/ragflow",
          "providers/recraft",
          "providers/replicate",
          { type: "category", label: "RunwayML", items: [
            "providers/runwayml/images",
            "providers/runwayml/videos",
          ] },
          "providers/sambanova",
          "providers/sap",
          "providers/sarvam",
          "providers/scaledown",
          "providers/scaleway",
          "providers/scx_ai",
          "providers/snowflake",
          "providers/stability",
          "providers/synthetic",
          "providers/tencent",
          "providers/tensormesh",
          "providers/togetherai",
          "providers/topaz",
          "providers/v0",
          "providers/volcano",
          "providers/voyage",
          "providers/wandb_inference",
          { type: "category", label: "WatsonX", items: [
            "providers/watsonx/index",
            "providers/watsonx/audio_transcription",
          ] },
          "providers/xiaomi_mimo",
          "providers/zai",
        ] },
        { type: "category", label: "Add a Provider", items: [
          { type: "doc", id: "provider_registration/index", label: "Integrate as a Model Provider" },
          { type: "doc", id: "contributing/adding_openai_compatible_providers", label: "Add OpenAI-Compatible Provider (JSON)" },
          { type: "doc", id: "provider_registration/add_model_pricing", label: "Add Model Pricing & Context Window" },
        ] },
      ],
    },


    { type: "html", value: "More", className: "sidebar-caption", defaultStyle: true },
    {
      type: "category",
      label: "Troubleshooting",
      items: [
        "troubleshoot/ui_issues",
        "troubleshoot/cost_discrepancy",
        "troubleshoot/missing_model",
        {
          type: "category",
          label: "Performance / Latency",
          items: [
            "troubleshoot/latency_overhead",
            "troubleshoot/cpu_issues",
            "troubleshoot/memory_issues",
            "troubleshoot/spend_queue_warnings",
            "troubleshoot/max_callbacks",
            "troubleshoot/prisma_migrations",
          ],
        },
        "troubleshoot/pip_venv_upgrade",
        "troubleshoot/rollback",
        "troubleshoot",
      ],
    },
    {
      type: "category",
      label: "Resources",
      items: [
        "sdk_custom_pricing",
        "migration",
        { type: "ref", id: "data_security" },
        { type: "ref", id: "proxy/security_encryption_faq" },
        "proxy/docker_image_security",
        "migration_policy",
        "api_stability_policy",
        { type: "ref", id: "shared_responsibility" },
        "proxy/release_cycle",
        "load_test_advanced",
        "load_test_sdk",
        "load_test_rpm",
        {
          type: "category",
          label: "❤️ 🚅 Projects built on LiteLLM",
          link: {
            type: "generated-index",
            title: "Projects built on LiteLLM",
            description:
              "Learn how to deploy + call models from different providers on LiteLLM",
            slug: "/project",
          },
          items: [
            "projects/smolagents",
            "projects/mini-swe-agent",
            "projects/openai-agents",
            "projects/Google ADK",
            "projects/Agent Lightning",
            "projects/Harbor",
            "projects/CompatCanary",
            "projects/GraphRAG",
            "projects/Docq.AI",
            "projects/PDL",
            "projects/OpenInterpreter",
            "projects/Elroy",
            "projects/dbally",
            "projects/FastREPL",
            "projects/PROMPTMETHEUS",
            "projects/Codium PR Agent",
            "projects/Prompt2Model",
            "projects/SalesGPT",
            "projects/Softgen",
            "projects/Quivr",
            "projects/Langstream",
            "projects/Otter",
            "projects/YiVal",
            "projects/llm_cord",
            "projects/pgai",
            "projects/GPTLocalhost",
            "projects/HolmesGPT",
            "projects/Railtracks",
          ],
        },
        "extras/code_quality",
        "rules",
        "proxy/team_based_routing",
        "proxy/customer_routing",
        "proxy_server",
      {
        type: "category",
        label: "Contributing",
        items: [
          "extras/contributing_code",
          {
            type: "category",
            label: "Adding Providers",
            items: [
              { type: "ref", id: "contributing/adding_openai_compatible_providers" },
              "adding_provider/directory_structure",
              "adding_provider/new_rerank_provider",
            ]
          },
          "extras/contributing",
          "contributing",
        ]
      },
      ],
    },
  ],
};

// ════════════════════════════════════════════════════════════
// ENTERPRISE (the Enterprise tab in the navbar)
// This sidebar holds only Enterprise pages, so a reader who opens the
// Enterprise tab stays in it. Feature docs (SSO, multi-region, budgets, and
// so on) stay in the Docs sidebar with the Enterprise pill. Readers reach
// them from the feature list on the Overview and from the Production rollout
// steps. "sidebar-group-label" draws the hairline and cluster name, and
// "sidebar-xlink" marks the few links that leave the tab.
// ════════════════════════════════════════════════════════════
const enterpriseSidebar = {
  enterpriseSidebar: [
    { type: "doc", id: "enterprise", label: "Overview" },
    { type: "doc", id: "learn/enterprise_quickstart", label: "Production rollout" },
    { type: "doc", id: "enterprise/activate", label: "Activate your license" },
    { type: "doc", id: "enterprise/moving_from_oss", label: "Moving from OSS" },
    { type: "html", value: "Features", className: "sidebar-group-label", defaultStyle: true },
    { type: "link", label: "All Enterprise features", href: "/docs/enterprise#full-feature-list" },
    { type: "doc", id: "proxy/multiple_admins", label: "Audit logs" },
    { type: "html", value: "Security review", className: "sidebar-group-label", defaultStyle: true },
    { type: "doc", id: "enterprise/compliance", label: "Compliance and SOC 2 Type II" },
    { type: "doc", id: "data_security", label: "Data privacy and security" },
    { type: "doc", id: "shared_responsibility", label: "Shared responsibility" },
    { type: "doc", id: "proxy/security_encryption_faq", label: "Security and encryption FAQ" },
    { type: "link", label: "Trust Center", href: "https://trust.litellm.ai/" },
    { type: "html", value: "Support", className: "sidebar-group-label", defaultStyle: true },
    { type: "doc", id: "enterprise/support", label: "Support and SLA" },
    { type: "doc", id: "enterprise/version_support", label: "Version support" },
    { type: "link", label: "Release notes", href: "/release_notes", className: "sidebar-xlink" },
    { type: "link", label: "Book a demo", href: "https://enterprise.litellm.ai/demo" },
  ],
};


const learnSidebar = {
  learnSidebar: [
    { type: "doc", id: "learn/index", label: "Overview" },
    { type: "html", value: "Quickstarts", className: "sidebar-caption", defaultStyle: true },
    "learn/gateway_quickstart",
    "learn/python_sdk_quickstart",
    "learn/enterprise_quickstart_learn",
    { type: "html", value: "Cookbook", className: "sidebar-caption", defaultStyle: true },
    {
      type: "category",
      label: "Connect apps and providers",
      link: { type: "generated-index", title: "Connect apps and providers", description: "Install the SDK, set provider keys, and send requests to models from different providers.", slug: "/learn/call-any-model" },
      items: [
        "tutorials/installation",
        "tutorials/first_playground",
        "tutorials/text_completion",
        "tutorials/mock_completion",
        "tutorials/provider_specific_params",
        "tutorials/gradio_integration",
        "tutorials/azure_openai",
        "tutorials/TogetherAI_liteLLM",
        "tutorials/huggingface_tutorial",
        "tutorials/huggingface_codellama",
        "tutorials/finetuned_chat_gpt",
        "tutorials/oobabooga",
      ],
    },
    {
      type: "category",
      label: "Control access",
      link: { type: "generated-index", title: "Control access", description: "Give access to teams and users, and connect your identity provider.", slug: "/learn/run-the-gateway" },
      items: [
        "tutorials/default_team_self_serve",
        "tutorials/msft_sso",
        "tutorials/tag_management",
      ],
    },
    {
      type: "category",
      label: "Control cost and capacity",
      link: { type: "generated-index", title: "Control cost and capacity", description: "Add fallbacks, use prompt caching, and send each request to the most suitable model.", slug: "/learn/cost-and-reliability" },
      items: [
        "tutorials/model_fallbacks",
        "tutorials/fallbacks",
        "tutorials/prompt_caching",
      ],
    },
    {
      type: "category",
      label: "Control content",
      link: { type: "generated-index", title: "Control content", description: "Add guardrails that examine requests and mask personal data before the model receives it.", slug: "/learn/add-safety" },
      items: [
        "tutorials/litellm_proxy_aporia",
        "tutorials/presidio_pii_masking",
      ],
    },
    {
      type: "category",
      label: "Connect tools and agents",
      link: { type: "generated-index", title: "Connect tools and agents", description: "Use LiteLLM with agent frameworks, coding tools, files, and vector stores.", slug: "/learn/agents-and-tools" },
      items: [
        "tutorials/file_search_responses_api",
        "tutorials/mongodb_vector_search",
        "tutorials/anthropic_file_usage",
        "tutorials/gemini_realtime_with_audio",
      ],
    },
    {
      type: "category",
      label: "See what happened",
      link: { type: "generated-index", title: "See what happened", description: "Send logs to observability tools and compare models on your own prompts.", slug: "/learn/observe-and-evaluate" },
      items: [
        "tutorials/elasticsearch_logging",
        "tutorials/compare_llms",
        "tutorials/litellm_Test_Multiple_Providers",
        "tutorials/eval_suites",
        "tutorials/lm_evaluation_harness",
      ],
    },
    "tutorials/index",
  ],
};


module.exports = { ...sidebars, ...enterpriseSidebar, ...learnSidebar };
